config/routes.rb
Rails.application.routes.draw do
  root 'houses#index'
  resources :houses
  resources :characters
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :house
end

app/models/house.rb
class House < ApplicationRecord
  has_many :characters, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.create!(character_params)
    redirect_to characters_path(@character)
  end

  def show
    @character = Character.find(params[:id])
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    @character.update(character_params)
    redirect_to characters_path(@character)
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
  end

  private
  def character_params
    params.require(:character).permit(:name, :img_url)
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
  end

  def new
    @house = House.new
  end

  def create
    @house = House.create!(house_params)
    redirect_to @house
  end

  def edit
    @house = House.find(params[:id])
  end

  def update
    @house = House.find(params[:id])
    redirect_to @house
  end

  def destroy
    @house = House.find(params[:id])
    @house.destroy
    redirect_to houses_path
  end

  private
  def house_params
    params.require(:house).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/characters/edit.html.erb
<%= form_for @character do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :img_url %>
<%= f.text_field :img_url %>

<%= f.submit %>

<% end %>

app/views/characters/index.html.erb
<div id="container">
<h2><%= link_to "Noble Westeros Houses", houses_path %></h2>
<h2>Characters <%= link_to "(+)", new_character_path %></h2>
</div>

<ul>
  <% @characters.each do |character| %>
    <li class="boxed">
      <%= link_to "#{character.name} - #{character.house.name}", character %>
    </li>
  <% end %>
</ul>

app/views/characters/new.html.erb
<%= form_for @character do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :img_url %>
<%= f.text_field :img_url %>

<%= f.submit %>

<% end %>

app/views/characters/show.html.erb
<h2><%= link_to "Noble Westeros Houses - Game of Thrones", houses_path %></h2>

<h2><%= @character.name %></h2>
<h2><%= "House " + @house.name %></h2>
<img src="<%= @character.img_url %>">

<% end %>

app/views/houses/edit.html.erb
<h2><%= link_to "Noble Westeros Houses - Game of Thrones", houses_path %></h2>
<h3>EDIT This House</h3>

<%= form_for @house do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :img_url %>
<%= f.text_field :img_url %>

<%= f.submit %>

<% end %>
<br/>
<img src="<%= @house.img_url %> " width="300px">

app/views/houses/index.html.erb
<div id="container">
<h2><%= link_to "Noble Westeros Houses - Game of Thrones", houses_path %></h2>


<h4><%= link_to "+ Add NEW House +", new_house_path %></h4>
</div>

<ul>
  <% @houses.each do |house| %>
  <li class="boxed">
    <h3><%= link_to "House " + house.name, house %></h3>
    <img src="<%= house.img_url %> " width="200px">
    <h5><%= link_to "[EDIT] House " + house.name, edit_house_path(house) %> |
        <%= link_to "[DELETE] House " + house.name, house_path(house),
    method: :delete,
    data: { confirm: "One does not simply DELETE a House. Are you CERTAIN?" } %></h5>
  </li>
  <% end %>
</ul>

app/views/houses/new.html.erb
<h2><%= link_to "Noble Westeros Houses - Game of Thrones", houses_path %></h2>
<h3>Add NEW House</h3>

<%= form_for @house do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :img_url %>
<%= f.text_field :img_url %>

<%= f.submit %>

<% end %>

app/views/houses/show.html.erb
<h2><%= link_to "Noble Westeros Houses", houses_path %></h2>
<h3><%= "House " + @house.name %></h3>
<img src="<%= @house.img_url %> " width="300px">
<h5><%= link_to "[EDIT] House " + @house.name, edit_house_path(@house) %> |
    <%= link_to "[DELETE] House " + @house.name, house_path(@house),
method: :delete,
data: { confirm: "One does not simply DELETE a House. Are you CERTAIN?" } %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thrones</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>